name: Python lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isort/isort-action@v1
        with:
          requirements-files: "./editor-blender/requirements.txt"
          sort-paths: "./editor-blender"
      - uses: psf/black@stable
        with:
            options: "--check --verbose"
            src: "./editor-blender"